[package]
authors = ["Vivian Hellyer <vivian@hellyer.dev>"]
description = "Utility crate for twilight-model to create mentions for resources."
documentation = "https://twilight.cascadia.cafe/twilight_mention/index.html"
edition = "2018"
homepage = "https://github.com/twilight-rs/twilight"
include = ["src/*.rs", "Cargo.toml", "README.md"]
keywords = ["twilight"]
license = "ISC"
name = "twilight-mention"
publish = false
repository = "https://github.com/twilight-rs/twilight.git"
readme = "README.md"
version = "0.1.0"

[dependencies]
twilight-model = { default-features = false, path = "../../model" }
