[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
documentation = "https://docs.rs/dawn-gateway"
edition = "2018"
homepage = "https://dawn.valley.cafe"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "dawn"]
license = "ISC"
name = "dawn-gateway"
publish = false
readme = "README.md"
repository = "https://github.com/dawn-rs/dawn.git"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
bitflags = "1"
dawn-http = { path = "../http" }
dawn-model = { path = "../model" }
futures = "0.3"
log = "0.4"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
serde-value = "0.6"
# Make it use less features at a later time.
tokio = { version = "0.2", features = ["full"] }
tokio-tungstenite = { git = "https://github.com/snapview/tokio-tungstenite.git", features = ["tls"] }
url = "2"
# The default backend for flate2; miniz-oxide, works differently
# from the C-backed backend zlib, When you give it the sync argument
# it does not seem to update the total_in of the function to have an offset
# https://github.com/alexcrichton/flate2-rs/issues/217
flate2 = { version = "1.0", default-features = false, features = ["zlib"] }

#optional
metrics = { version = "0.12.1", optional = true }

[dev-dependencies]
futures = "0.3"
tokio = "0.2"

[features]
default = []
