[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
documentation = "https://docs.rs/dawn-gateway"
edition = "2018"
homepage = "https://dawn.valley.cafe"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "dawn"]
license = "ISC"
name = "dawn-gateway"
publish = false
readme = "README.md"
repository = "https://github.com/dawn-rs/dawn.git"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
bitflags = "1"
dawn-cache-trait = { optional = true, path = "../cache/trait" }
dawn-http = { path = "../http" }
dawn-model = { path = "../model" }
futures-channel-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
log = "0.4"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
serde-value = "0.6"
tokio-executor = "0.2.0-alpha.6"
tokio-net = "0.2.0-alpha.6"
tokio-timer = "0.3.0-alpha.6"
tokio-tungstenite = { git = "https://github.com/dbcfd/tokio-tungstenite", branch = "tokio2" }
url = "2"
# The default backend for flate2; miniz-oxide, works differently
# from the C-backed backend zlib, When you give it the sync argument
# it does not seem to update the total_in of the function to have an offset
flate2 = { version = "1.0", default-features = false, features = ["zlib"] }

[dev-dependencies]
futures-preview = "0.3.0-alpha.19"
tokio = "0.2.0-alpha.6"

[features]
default = ["cache"]
cache = ["dawn-cache-trait"]
