[package]
authors = ["Twilight Contributors"]
categories = ["api-bindings", "asynchronous", "web-programming::websocket"]
description = "Discord Gateway implementation for the Twilight ecosystem."
documentation = "https://docs.rs/twilight-gateway"
edition = "2018"
homepage = "https://twilight.rs/chapter_1_crates/section_3_gateway.html"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-gateway"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.1.2"

[dependencies]
async-tungstenite = { default-features = false, features = ["tokio-runtime"], version = "0.8" }
bitflags = { default-features = false, version = "1" }
twilight-http = { default-features = false, path = "../http" }
twilight-model = { default-features = false, path = "../model" }
twilight-gateway-queue = { default-features = false, path = "./queue" }
futures-channel = { default-features = false, features = ["sink"], version = "0.3" }
futures-util = { default-features = false, features = ["std"], version = "0.3" }
tracing = { default-features = false, features = ["std", "attributes"], version = "0.1" }
once_cell = { default-features = false, features = ["std"], version = "1" }
serde = { default-features = false, features = ["derive"], version = "1" }
serde_json = { default-features = false, version = "1" }
tokio = { default-features = false, features = ["net", "rt-core", "sync"], version = "0.2" }
url = { default-features = false, version = "2" }
# The default backend for flate2; miniz-oxide, works differently
# from the C-backed backend zlib, When you give it the sync argument
# it does not seem to update the total_in of the function to have an offset
# https://github.com/alexcrichton/flate2-rs/issues/217
flate2 = { default-features = false, version = "1.0" }
dashmap = { default-features = false, version = "3" }

# optional
metrics = { default-features = false, optional = true, version = "0.12.1" }
simd-json = { default-features = false, features = ["serde_impl", "swar-number-parsing"], optional = true, version = "0.3" }

[dev-dependencies]
futures = { default-features = false, version = "0.3" }
static_assertions = { default-features = false, version = "1" }
tokio = { default-features = false, features = ["rt-core", "macros"], version = "0.2" }

[features]
default = ["rustls", "stock-zlib"]
native = ["twilight-http/native", "twilight-gateway-queue/native", "async-tungstenite/tokio-native-tls"]
rustls = ["twilight-http/rustls", "twilight-gateway-queue/rustls", "async-tungstenite/async-tls"]
simd-zlib = ["flate2/zlib-ng-compat"]
# if the `zlib` feature is enabled anywhere in the dependency tree it will
# always use stock zlib instead of zlib-ng.
# https://github.com/rust-lang/libz-sys/blob/main/README.md#zlib-ng
stock-zlib = ["flate2/zlib"]
