[package]
authors = ["Twilight Contributors"]
documentation = "https://docs.rs/twilight-standby"
edition = "2018"
homepage = "https://github.com/twilight-rs/twilight/tree/trunk/standby"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-standby"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.1.0"

[dependencies]
dashmap = { default-features = false, version = "3" }
futures-channel = { default-features = false, features = ["std"], version = "0.3" }
futures-util = { default-features = false, features = ["std"], version = "0.3" }
log = { default-features = false, version = "0.4" }
twilight-model = { default-features = false, path = "../model" }

[dev-dependencies]
twilight-gateway = { path = "../gateway" }
tokio = { default-features = false, features = ["macros", "rt-core"], version = "0.2" }
