[package]
authors = ["Zeyla Hellyer <zeyla@hellyer.dev>"]
documentation = "https://docs.rs/dawn-http"
edition = "2018"
homepage = "https://github.com/dawn-rs/dawn"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "dawn"]
license = "ISC"
name = "dawn-http"
publish = false
readme = "README.md"
repository = "https://github.com/dawn-rs/dawn.git"
version = "0.1.0"

[dependencies]
futures-channel-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
futures-timer = "0.5"
dawn-model = { path = "../model" }
log = "0.4"
reqwest = { default-features = false, version = "0.10.0-alpha.1" }
serde = "1"
serde_json = "1"
tokio-executor = "0.2.0-alpha.6"

[dev-dependencies]
tokio = "0.2.0-alpha.6"
