[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
documentation = "https://docs.rs/twilight-http"
edition = "2018"
homepage = "https://github.com/twilight-rs/twilight"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-http"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.1.0"

[dependencies]
bytes = { default-features = false, version = "0.5" }
futures-channel = { default-features = false, version = "0.3" }
futures-util = { default-features = false, features = ["std"], version = "0.3" }
twilight-model = { default-features = false, features = ["serde-support"], path = "../model" }
log = { default-features = false, version = "0.4" }
reqwest = { default-features = false, version = "0.10" }
serde = { default-features = false, features = ["derive"], version = "1" }
serde_json = { default-features = false, optional = true, version = "1" }
serde_repr = { default-features = false, version = "0.1" }
simd-json = { default-features = false, optional = true, version = "0.3" }
tokio = { default-features = false, version = "0.2" }
percent-encoding = { default-features = false, version = "2" }
url = { default-features = false, version = "2" }

[features]
default = ["native", "serde_json"]
native = ["reqwest/default-tls"]
rustls = ["reqwest/rustls-tls"]

[dev-dependencies]
serde_test = { default-features = false, version = "1" }
tokio = { default-features = false, features = ["macros", "rt-core"], version = "0.2" }
