[package]
authors = ["Twilight Contributors"]
categories = ["api-bindings", "asynchronous", "web-programming::http-client"]
description = "Discord REST API client for the Twilight ecosystem."
documentation = "https://docs.rs/twilight-http"
edition = "2018"
homepage = "https://twilight.rs/chapter_1_crates/section_2_http.html"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-http"
publish = false
readme = "README.md"
repository = "https://github.com/twilight-rs/twilight.git"
version = "0.1.1"

[dependencies]
bytes = { default-features = false, version = "0.5" }
futures-channel = { default-features = false, version = "0.3" }
futures-util = { default-features = false, features = ["std"], version = "0.3" }
twilight-model = { default-features = false, path = "../model" }
tracing = { default-features = false, features = ["std", "attributes"], version = "0.1" }
reqwest = { default-features = false, version = "0.10" }
serde = { default-features = false, features = ["derive"], version = "1" }
serde_json = { default-features = false, version = "1" }
serde_repr = { default-features = false, version = "0.1" }
tokio = { default-features = false, version = "0.2" }
percent-encoding = { default-features = false, version = "2" }
url = { default-features = false, version = "2" }

# optional
simd-json = { default-features = false, features = ["serde_impl", "swar-number-parsing"], optional = true, version = "0.3" }

[features]
default = ["rustls"]
native = ["reqwest/default-tls"]
rustls = ["reqwest/rustls-tls"]

[dev-dependencies]
serde_test = { default-features = false, version = "1" }
tokio = { default-features = false, features = ["macros", "rt-core"], version = "0.2" }
