[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-gateway-example-queue"
version = "0.1.0"

[dependencies]
twilight-gateway = { path = "../.." }
futures = "0.3"
tracing-subscriber = "0.2"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
async-trait = "0.1"
