name: Cargo Audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - '**/Cargo.toml'
  pull_request:
    paths:
      - '**/Cargo.toml'

jobs:
  audit:
    name: Cargo Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install cargo-audit
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true

      - name: Run cargo-audit
        run: cargo audit
