name: Cargo Audit

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    paths:
      - '**/Cargo.toml'
  pull_request:
    paths:
      - '**/Cargo.toml'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Run cargo-audit
      run: cargo audit
