name: Cargo Audit

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    paths:
      - '**/Cargo.toml'
  pull_request:
    paths:
      - '**/Cargo.toml'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-audit
        version: latest
        use-tool-cache: true
    - name: Run cargo-audit
      run: cargo audit
