name: Check Documentation

on: [push, pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
    - name: Build docs
      env:
        RUSTDOCFLAGS: -D intra_doc_link_resolution_failure
      run: cargo doc --no-deps

  sync-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-sync-readme
        version: latest
    - name: Run in builders
      run: cd builders && cargo sync-readme --check
    - name: Run in command-parser
      run: cd command-parser && cargo sync-readme --check
    - name: Run in gateway
      run: cd gateway && cargo sync-readme --check
    - name: Run in http
      run: cd http && cargo sync-readme --check
    - name: Run in lavalink
      run: cd lavalink && cargo sync-readme --check
    - name: Run in model
      run: cd model && cargo sync-readme --check
    - name: Run in standby
      run: cd standby && cargo sync-readme --check
    - name: Run in twilight
      run: cd twilight && cargo sync-readme --check
