[package]
authors = ["Twilight Contributors"]
description = "Advertisement crate for the twilight ecosystem; please use the individual crates instead."
documentation = "https://docs.rs/twilight"
edition = "2018"
homepage = "https://twilight.rs"
include = ["src/**/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight"
publish = false
repository = "https://github.com/twilight-rs/twilight"
readme = "../README.md"
version = "0.1.0"

[dev-dependencies]
tokio = { default-features = false, features = ["macros", "rt-core"], version = "0.2" }
tracing-log = { default-features = false, features = ["log-tracer", "std"], version = "0.1" }
twilight-cache-inmemory = { default-features = false, path = "../cache/in-memory" }
twilight-gateway = { default-features = false, features = ["rustls"], path = "../gateway" }
twilight-http = { default-features = false, features = ["rustls"], path = "../http" }
twilight-model = { path = "../model" }
