[package]
authors = ["Valdemar Erk <valdemar@erk.io>"]
documentation = "https://docs.rs/twilight"
edition = "2018"
homepage = "https://github.com/twilight-rs/twilight"
include = ["src/*.rs", "Cargo.toml"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight"
publish = false
repository = "https://github.com/twilight-rs/twilight"
readme = "../README.md"
version = "0.1.0"

[dependencies]
twilight-builders = { optional = true, path = "../builders" }
twilight-cache = { optional = true, path = "../cache/base" }
twilight-command-parser = { optional = true, path = "../command-parser" }
twilight-gateway = { default-features = false, optional = true, path = "../gateway" }
twilight-http = { default-features = false, optional = true, path = "../http" }
twilight-model = { optional = true, path = "../model" }
twilight-standby = { optional = true, path = "../standby" }

[dev-dependencies]
tokio = { default-features = false, features = ["macros", "rt-core"], version = "0.2" }

[features]
default = ["all", "native"]

all = ["builders", "cache", "command-parser", "gateway", "http", "model", "standby"]
builders = ["twilight-builders"]
cache = ["twilight-cache"]
command-parser = ["twilight-command-parser"]
gateway = ["twilight-gateway"]
http = ["twilight-http"]
model = ["twilight-model"]
standby = ["twilight-standby"]
simd-json = ["twilight-gateway/simd-json", "twilight-http/simd-json"]
native = ["twilight-gateway/native", "twilight-http/native"]
rustls = ["twilight-gateway/rustls", "twilight-http/rustls"]

metrics = ["gateway-metrics"]
gateway-metrics = ["gateway", "twilight-gateway/metrics"]
